### ISSUE TITLE
Issue with the included "tape intro" sample 

### ISSUE THREAD

**Issue by evanc** [orllewin/playdate_tape_looper#1]
(Obviously this is a pretty minor issue...) When I play the included "tape intro" sample it plays through fine, but when it reaches the end of the sample it continues playing. You hear some distorted noises and the progress bar continues past the end of its container. Eventually it wraps back around to the beginning as expected. While messing around with this I found that sometimes if you set a cue outside of the regular playback area of the sound, the app crashes.

This is happening on an actual playdate device.

**Comment by orllewin** [comment]
Yes, I'm hearing/seeing this too, I made a mental note to exclude that intro file from the file select as a quick fix but forgot before I launched the app! It must be something to do with the file already being loaded into a fileplayer for the intro sequence, there is a close/release call I think, will investigate.

**Comment by orllewin** [comment]
this is redundant now, with TL2
